trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)
- stage: Deploy
  displayName: Deploy to EC2
  jobs:
  - job: Deploy
    displayName: Deploy to EC2
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SSH@0
      displayName: 'SSH to EC2'
      inputs:
        sshEndpoint: 'azure-teste-local'
        runOptions: 'inline'
        inline: |
          sudo docker stop backend-api || true
          sudo docker rm backend-api || true
          sudo docker run -d --name backend-api -p 3100:3100 $(tag)
